refactor: tabs for indentation and spaces for alignment
Signed-off-by: Charles Moscofian <charlesmoscofian@hotmail.com>

diff --git a/utils/print b/utils/print
--- a/utils/print
+++ b/utils/print
@@ -7,33 +7,34 @@ __cyan="\033[1;36m"
 __grey="\033[1;38;5;243m"
 __default="\033[0m"
 
-
-function print::title() {
-    echo -e "${__purple}$1${__default}"
-    echo -e "${__grey}==============================${__default}"
+print::title() {
+	echo -e "${__purple}$1${__default}"
+	echo -e "${__grey}==============================${__default}"
 }
 
-function print::error() {
-    echo -e "${__red}[error]${__default}: $1"
+print::error() {
+	echo -e "${__red}[error]${__default}: $1"
 }
 
-function print::warning() {
-    echo -e "${__yellow}[warning]${__default}: $1"
+print::warning() {
+	echo -e "${__yellow}[warning]${__default}: $1"
 }
 
-function print::info() {
-    echo -e "${__cyan}[info]${__default}: $1"
+print::info() {
+	echo -e "${__cyan}[info]${__default}: $1"
 }
 
-function print::success() {
-    echo -e "${__green}[success]${__default}: $1"
+print::success() {
+	echo -e "${__green}[success]${__default}: $1"
 }
 
-function print::colors() {
-    for i in {0..255} ; do
-        printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
-        if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
-            printf "\n";
-        fi
-    done
+print::colors() {
+	for i in {0..255} ; do
+		printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
+		if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
+			printf "\n";
+		fi
+	done
 }
+
+# vim: ft=bash
