Change vim theme from nord to nibble and formatting
This commit replaces nord as a primary color theme in favor of nibble
for vim and also add a terminal scheme for nibble

Also format all files with "retab" and bump sub modules versions

diff --git a/shell/functions/workupt b/shell/functions/workupt
--- a/shell/functions/workupt
+++ b/shell/functions/workupt
@@ -9,93 +9,93 @@
 #
 # Author: Charles Moscofian <charlesmoscofian@hotmail.com>
 function f::workupt() {
-	local __branch="develop"
-	local __remote="origin"
+    local __branch="develop"
+    local __remote="origin"
 
-	local __opt
-	local __help=0
+    local __opt
+    local __help=0
 
-	while getopts ":b:r:h" __opt; do
-		case $__opt in
-			b) __branch=$OPTARG;;
-			r) __remote=$OPTARG;;
-			h) __help=1;;
-			\?) ;;
-		esac
-	done
-	shift $(( OPTIND - 1 ))
+    while getopts ":b:r:h" __opt; do
+        case $__opt in
+            b) __branch=$OPTARG;;
+            r) __remote=$OPTARG;;
+            h) __help=1;;
+            \?) ;;
+        esac
+    done
+    shift $(( OPTIND - 1 ))
 
-	if [ $__help -eq 1 ]; then
-		echo -e "USAGE: $0 [-b branch] [-r remote] [-h] path\n"
-		return 0
-	fi
+    if [ $__help -eq 1 ]; then
+        echo -e "USAGE: $0 [-b branch] [-r remote] [-h] path\n"
+        return 0
+    fi
 
-	if [ ! -d $1 ] || [ -z $1 ]; then
-		print::error "not a valid workspace directory"
-		return 1
-	fi
+    if [ ! -d $1 ] || [ -z $1 ]; then
+        print::error "not a valid workspace directory"
+        return 1
+    fi
 
-	print::info "updating against \"$__remote/$__branch\"..."
+    print::info "updating against \"$__remote/$__branch\"..."
 
-	local __path=$PWD
-	local __workspace=$1
+    local __path=$PWD
+    local __workspace=$1
 
-	cd $__workspace
+    cd $__workspace
 
-	local __i_workspace
-	for __i_workspace in $(ls); do
-		[ ! -d $__i_workspace ] && continue
+    local __i_workspace
+    for __i_workspace in $(ls); do
+        [ ! -d $__i_workspace ] && continue
 
-		cd $__i_workspace
-		local __msg="project $__i_workspace"
+        cd $__i_workspace
+        local __msg="project $__i_workspace"
 
-		if git::is_worktree; then
-			git switch --no-guess $__branch &> /dev/null
-			if [ $? -ne 0 ]; then
-				print::error "${__msg} unable to switch to branch $__branch"
-				cd ..
-				continue
-			fi
+        if git::is_worktree; then
+            git switch --no-guess $__branch &> /dev/null
+            if [ $? -ne 0 ]; then
+                print::error "${__msg} unable to switch to branch $__branch"
+                cd ..
+                continue
+            fi
 
-			if [ ! -z $__remote ]; then
-				git fetch $__remote &> /dev/null
-				if [ $? -ne 0 ]; then
-					print::error "${__msg} unable to fetch from remote $__remote"
-					cd ..
-					continue
-				fi
+            if [ ! -z $__remote ]; then
+                git fetch $__remote &> /dev/null
+                if [ $? -ne 0 ]; then
+                    print::error "${__msg} unable to fetch from remote $__remote"
+                    cd ..
+                    continue
+                fi
 
-				git pull $__remote $_branch &> /dev/null
-				if [ $? -ne 0 ]; then
-					print::error "${__msg} unable to pull from remote $__remote into branch $__branch"
-					cd ..
-					continue
-				fi
-			else
-				git fetch --all &> /dev/null
-				if [ $? -ne 0 ]; then
-					print::error "${__msg} unable to fetch from ANY remote"
-					cd ..
-					continue
-				fi
+                git pull $__remote $_branch &> /dev/null
+                if [ $? -ne 0 ]; then
+                    print::error "${__msg} unable to pull from remote $__remote into branch $__branch"
+                    cd ..
+                    continue
+                fi
+            else
+                git fetch --all &> /dev/null
+                if [ $? -ne 0 ]; then
+                    print::error "${__msg} unable to fetch from ANY remote"
+                    cd ..
+                    continue
+                fi
 
-				git pull origin $__branch &> /dev/null
-				if [ $? -ne 0 ]; then
-					print::error "${__msg} unable to pull from remote origin into branch $__branch"
-					cd ..
-					continue
-				fi
-			fi
-			print::success "${__msg}"
-			cd ..
-		else
-			print::error "$__i_workspace is not a git directory"
-			cd ..
-		fi
-	done
+                git pull origin $__branch &> /dev/null
+                if [ $? -ne 0 ]; then
+                    print::error "${__msg} unable to pull from remote origin into branch $__branch"
+                    cd ..
+                    continue
+                fi
+            fi
+            print::success "${__msg}"
+            cd ..
+        else
+            print::error "$__i_workspace is not a git directory"
+            cd ..
+        fi
+    done
 
-	cd $__path
+    cd $__path
 
-	return 0
+    return 0
 }
 
