refactor(shell): helper functions accept multiple workspaces
Adapted the workspace functions listed below to accept multiple
workspaces and iterate over them when running it's logic.
    * f::branches
    * f::workset
    * f::workupt

Also, removed invalid alias, adjust tmux config and bump nvim plugins.

diff --git a/shell/functions/workupt b/shell/functions/workupt
--- a/shell/functions/workupt
+++ b/shell/functions/workupt
@@ -1,9 +1,9 @@
 # A simple function to fetch and update all git projects at once based on a
 # branch and a remote
 #
-# USAGE: f::workupt [-b branch] [-r remote] [-h] path
+# USAGE: f::workupt [-b branch] [-r remote] [-h] ...paths
 #
-# [path]: Path to the workspace directory where all git projects reside
+# [paths]: Paths to the workspace directories where all git projects reside
 # [branch]: Branch to switch into and fast-forward agains. Default: "develop"
 # [remote]: Remote from which all changes will be fetched. Default: "origin"
 #
@@ -30,71 +30,69 @@ function f::workupt() {
         return 0
     fi
 
-    if [ ! -d $1 ] || [ -z $1 ]; then
-        print::error "not a valid workspace directory"
-        return 1
-    fi
-
-    print::info "updating against \"$__remote/$__branch\"..."
-
     local __path=$PWD
-    local __workspace=$1
-
-    cd $__workspace
-
+    local __workspace
     local __i_workspace
-    for __i_workspace in $(ls); do
-        [ ! -d $__i_workspace ] && continue
+    print::info "updating against \"$__remote/$__branch\"..."
+    for __workspace in $@; do
+        ([ ! -d $__workspace ] || [ -z $__workspace ]) && continue
 
-        cd $__i_workspace
-        local __msg="project $__i_workspace"
+        cd $__workspace
+        print::title "checking into workspace $__workspace"
 
-        if git::is_worktree; then
-            git switch --no-guess $__branch &> /dev/null
-            if [ $? -ne 0 ]; then
-                print::error "${__msg} unable to switch to branch $__branch"
+        for __i_workspace in $(ls); do
+            ([ ! -d $__i_workspace ] || [ -z $__i_workspace ]) && continue
+
+            cd $__i_workspace
+            local __msg="project $__i_workspace"
+
+            if git::is_worktree; then
+                git switch --no-guess $__branch &> /dev/null
+                if [ $? -ne 0 ]; then
+                    print::error "${__msg} unable to switch to branch $__branch"
+                    cd ..
+                    continue
+                fi
+
+                if [ ! -z $__remote ]; then
+                    git fetch $__remote &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        print::error "${__msg} unable to fetch from remote $__remote"
+                        cd ..
+                        continue
+                    fi
+
+                    git pull $__remote $_branch &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        print::error "${__msg} unable to pull from remote $__remote into branch $__branch"
+                        cd ..
+                        continue
+                    fi
+                else
+                    git fetch --all &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        print::error "${__msg} unable to fetch from ANY remote"
+                        cd ..
+                        continue
+                    fi
+
+                    git pull origin $__branch &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        print::error "${__msg} unable to pull from remote origin into branch $__branch"
+                        cd ..
+                        continue
+                    fi
+
+                fi
+
+                git gc --prune --aggressive &> /dev/null
+                print::success "${__msg}"
                 cd ..
-                continue
-            fi
-
-            if [ ! -z $__remote ]; then
-                git fetch $__remote &> /dev/null
-                if [ $? -ne 0 ]; then
-                    print::error "${__msg} unable to fetch from remote $__remote"
-                    cd ..
-                    continue
-                fi
-
-                git pull $__remote $_branch &> /dev/null
-                if [ $? -ne 0 ]; then
-                    print::error "${__msg} unable to pull from remote $__remote into branch $__branch"
-                    cd ..
-                    continue
-                fi
             else
-                git fetch --all &> /dev/null
-                if [ $? -ne 0 ]; then
-                    print::error "${__msg} unable to fetch from ANY remote"
-                    cd ..
-                    continue
-                fi
-
-                git pull origin $__branch &> /dev/null
-                if [ $? -ne 0 ]; then
-                    print::error "${__msg} unable to pull from remote origin into branch $__branch"
-                    cd ..
-                    continue
-                fi
-
+                print::error "$__i_workspace is not a git directory"
+                cd ..
             fi
-
-            git gc --prune --aggressive &> /dev/null
-            print::success "${__msg}"
-            cd ..
-        else
-            print::error "$__i_workspace is not a git directory"
-            cd ..
-        fi
+        done
     done
 
     cd $__path
